/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** CallGuardrail */
        post: operations["call-guardrail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/signals/ingest/v1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest signals (v1) */
        post: operations["ingest-signals-v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Call: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            /** Format: date-time */
            CreatedAt: string;
            CreatedBy: string;
            /** Format: int64 */
            DurationMs: number;
            GuardrailID: string;
            ID: string;
            Metadata: {
                [key: string]: unknown;
            };
            /** @enum {string} */
            Outcome: "pass" | "fail" | "error";
            Payload: components["schemas"]["Payload"];
            SummarisedEntries: components["schemas"]["SummarisedEntry"][];
            TenantID: string;
            /** Format: date-time */
            UpdatedAt: string;
            UpdatedBy: string;
        };
        CallGuardrailRequestBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            GuardrailID: string;
            Payload: components["schemas"]["Payload"];
            TenantID: string;
        };
        ChatInput: {
            Messages?: components["schemas"]["SimpleMessage"][];
            Settings: components["schemas"]["SimpleOptions"];
        };
        ChatOutput: {
            Messages?: components["schemas"]["SimpleMessage"][];
            Settings: components["schemas"]["SimpleOptions"];
        };
        CompletionPayload: {
            Context?: components["schemas"]["CompletionPayloadContext"];
            Input?: components["schemas"]["Input"];
            Model: string;
            Options: components["schemas"]["SimpleOptions"];
            Output?: components["schemas"]["Output"];
        };
        CompletionPayloadContext: {
            ParsedSystem: string;
            RetrievedItems: components["schemas"]["RetrievedItem"][];
        };
        CreateEventParams: {
            /** Format: date-time */
            At?: string | null;
            Attributes?: {
                [key: string]: unknown;
            };
            EntryID?: string | null;
            Name: string;
            SpanID?: string | null;
            TraceID?: string | null;
            XID: string;
        };
        CreateFindingParams: {
            /** Format: date-time */
            At?: string | null;
            Comment?: string | null;
            Description?: string | null;
            EntryID?: string | null;
            Metadata?: {
                [key: string]: unknown;
            };
            Name: string;
            Source?: string | null;
            SpanID?: string | null;
            TraceID?: string | null;
            Value: number | boolean | string;
            XID: string;
        };
        CreateSessionParams: {
            Attributes?: {
                [key: string]: unknown;
            };
            Name?: string | null;
            XID: string;
        };
        CreateSpanParams: {
            Attributes?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            End: string | null;
            Family?: string | null;
            FamilyData?: unknown;
            Message?: string | null;
            Name: string;
            ParentID?: string | null;
            Severity?: string | null;
            /** Format: date-time */
            Start: string;
            TraceID: string;
            XID: string;
        };
        CreateTraceParams: {
            Attributes?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            End?: string | null;
            Name?: string | null;
            SessionID?: string | null;
            /** Format: date-time */
            Start: string;
            XID: string;
        };
        EmbeddingsPayload: {
            Inputs: string[];
            Options: components["schemas"]["SimpleOptions"];
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            /** @description A human-readable explanation specific to this occurrence of the problem. */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][];
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             */
            status?: number;
            /** @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error. */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             */
            type: string;
        };
        Event: {
            /** Format: date-time */
            At: string;
            Attributes: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            CreatedAt: string;
            EntryID: string | null;
            ID: string;
            Name: string;
            SpanID: string | null;
            TenantID: string;
            TraceID: string | null;
            /** Format: date-time */
            UpdatedAt: string;
            XID: string;
        };
        Finding: {
            /** Format: date-time */
            At: string;
            Comment: string;
            /** Format: date-time */
            CreatedAt: string;
            EntryID: string | null;
            EvaluatorID: string | null;
            ID: string;
            Metadata: {
                [key: string]: unknown;
            };
            Name: string;
            /** @enum {string} */
            Source: "annotation" | "api" | "enduser" | "evaluator";
            SpanID: string | null;
            TenantID: string;
            TraceID: string | null;
            /** Format: date-time */
            UpdatedAt: string;
            Value: number | boolean | string;
            XID: string;
        };
        Function: {
            Arguments: unknown;
            Name: string;
        };
        IngestSignalsV1RequestBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            Events?: components["schemas"]["CreateEventParams"][];
            Findings?: components["schemas"]["CreateFindingParams"][];
            Sessions?: components["schemas"]["CreateSessionParams"][];
            Spans?: components["schemas"]["CreateSpanParams"][];
            Traces?: components["schemas"]["CreateTraceParams"][];
        };
        Input: {
            Chat?: components["schemas"]["ChatInput"];
            Text?: components["schemas"]["TextInput"];
        };
        OtherPayload: Record<string, never>;
        Output: {
            Chat?: components["schemas"]["ChatOutput"];
            Text?: components["schemas"]["TextOutput"];
        };
        Payload: {
            Input?: components["schemas"]["Input"];
            Output?: components["schemas"]["Output"];
        };
        RetrievalPayload: {
            Queries: components["schemas"]["RetrievalQuery"][];
            Retrieved: components["schemas"]["RetrievedItem"][];
        };
        RetrievalQuery: {
            Embeddings: number[];
            Name: string;
        };
        RetrievedItem: {
            Content: unknown;
            ContentType: string;
            Identifier: string;
            Metadata: {
                [key: string]: unknown;
            };
        };
        SimpleMessage: {
            Contents: components["schemas"]["SimplePart"][];
            Name?: string;
            /** @enum {string} */
            Role: "system" | "user" | "assistant" | "tool" | "function";
            ToolCallID?: string;
            ToolCalls?: components["schemas"]["ToolCall"][];
        };
        SimpleOptions: {
            /** Format: double */
            FrequencyPenalty?: number;
            Logprobs?: boolean;
            /** Format: int64 */
            MaxTokens?: number;
            /** Format: int64 */
            N?: number;
            /** Format: double */
            PresencePenalty?: number;
            /** Format: int64 */
            Seed?: number;
            Stream?: boolean;
            /** Format: double */
            Temperature?: number;
            /** Format: double */
            Timeout?: number;
            ToolChoice?: string;
            Tools?: components["schemas"]["Tool"][];
            /** Format: int64 */
            TopLogprobs?: number;
            /** Format: double */
            TopP?: number;
            User?: string;
        };
        SimplePart: {
            /** @enum {string} */
            Detail?: "auto" | "low" | "high";
            MimeType?: string;
            Text: string;
            URI?: string;
        };
        SimplifiedFinding: {
            /** Format: date-time */
            At: string;
            Comment: string;
            EvaluatorID: string | null;
            Metadata: {
                [key: string]: unknown;
            };
            Name: string;
            /** @enum {string} */
            Source: "annotation" | "api" | "enduser" | "evaluator";
            Value: number | boolean | string;
        };
        Span: {
            Attributes: {
                [key: string]: unknown;
            };
            Completion: components["schemas"]["CompletionPayload"];
            /** Format: date-time */
            CreatedAt: string;
            Embeddings: components["schemas"]["EmbeddingsPayload"];
            /** Format: date-time */
            End: string;
            Events: components["schemas"]["Event"][];
            Family: string;
            Findings: components["schemas"]["Finding"][];
            ID: string;
            Message: string;
            Name: string;
            Other: components["schemas"]["OtherPayload"];
            ParentID: string | null;
            Retrieval: components["schemas"]["RetrievalPayload"];
            Severity: string;
            /** Format: date-time */
            Start: string;
            TenantID: string;
            TraceID: string;
            /** Format: date-time */
            UpdatedAt: string;
            XID: string;
        };
        SummarisedEntry: {
            /** Format: int64 */
            DurationMs: number;
            EvaluatorID: string;
            Findings: components["schemas"]["SimplifiedFinding"][];
            ID: string;
            InstanceID: string | null;
            Message: string;
            Outcome: string;
            /** Format: double */
            Score: number | null;
            Skip: string;
            TenantID: string;
        };
        TextInput: {
            Text: string;
        };
        TextOutput: {
            Text: string;
        };
        Tool: {
            Description: string;
            Name: string;
            Parameters: unknown;
        };
        ToolCall: {
            Function: components["schemas"]["Function"];
            ID: string;
            /** @enum {string} */
            Type: "function";
        };
        TraceWithSpans: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            Attributes: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            CreatedAt: string;
            /** Format: date-time */
            End: string;
            ID: string;
            Name: string;
            SessionID: string | null;
            Spans: components["schemas"]["Span"][];
            /** Format: date-time */
            Start: string;
            TenantID: string;
            /** Format: date-time */
            UpdatedAt: string;
            XID: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "call-guardrail": {
        parameters: {
            query?: {
                dryrun?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CallGuardrailRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Call"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ingest-signals-v1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestSignalsV1RequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceWithSpans"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
